language: node_js
node_js:
- '8'


script:
- npm run lint
- npm run test


before_deploy:
- npm pack
- ls -a | grep -v ".tgz"  | xargs rm -rf
- tar xf *.tgz
- cd package/
deploy:
  provider: heroku
  api_key:
    secure: O+r95DHeFrni1NPtRbFZBlqNUwkcieSSfqQpT0pBBi+ZuoVlyPLvdwCTRhCRMDYxvoIHVB/mPjY8K8f60h4miKjSK1smlajhrwdPXFoLIXXxeMv+QlpWYVA5dZUl3CRn1ajEDosMXySOB/iHgLM9JfWOgnk4lwZGlesrsMMFAaQLHZPGABXxvqu+vuKP8bCJRTL2jm7Gt5b6X/yIKuVtAEJkCYfRNnd1jle2RJbEAFnL50G4X1XTrWylMYL4PnJD+6dIdrS7hp0c5Refjy1+3b+uLHw7r+a6YbotBDEpGuAQl4MBDVuCvvQ9FpMNG689WYeqZzpQpRKnuNv9zjQFXYm1aImhjqaBxfRDcgDvOyeKdCTq7x8Lj54MqCDF2l6Wg23tkOvkiTKmJhgvpyossVKOAgdSmNRgSB2WKZ1p6Ey7JGW9f8nIbnHDHbPDwhLtArZ8PvzyxFKL1I80d8nQ0ih4K0bs7hrte9qUAm3slQ/fozxSbkzCl8q0k18QfYecC3cfuoDk2Xb7Zr3pEoRlX7ErstmvqsT7082cpk53kRkJEc2BfULe7QQqm0hyXm3q+xeIUt7Dh78DiIFkZXHyV1Yz410EI2rqyTF3mUnmiD2EFY16WHZQKDgo3CXtaHPlNyG8+aqoRLVkP1ZE5WBApjwLmnvv8cCDDSrn5iRcmjs=
